### PR TITLE
Bugfix array attributes

### PR DESCRIPTION
**Pull request by gerb-ster**
Possible fix for issue #45

### CODE REVIEW

**Comment by cjmellor** [comment]
@gerb-ster I've just inlined the test, and just changed few bits to match my style.

Interesting way of fixing this, I wouldn't have even thought of this way, haha.

If you're happy with my change, approve it and I can merge.

**Comment by nunodonato** [comment]
@gerb-ster please approve this :D

**Comment by cjmellor** [comment]
Didn't want to wait much longer so just gonna merge it

**Comment by gerb-ster** [comment]
@cjmellor Sorry, got a bit side-tracked :) thx for merging it!

**Comment by nunodonato** [comment]
yay, thanks :D

**Pull request merged**
